---
- name: calico_setup | Install calico pod network
  become: false
  ansible.builtin.command: "{{ item }}"
  with_items:
    - kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
    - kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml
  args:
    creates: "./calico_is_installed"
