---
- name: Create namespace for ArgoCD
  kubectl:
    namespace: argocd
    name: argocd
    state: present
    api_version: v1
    kind: Namespace

- name: Apply ArgoCD manifests
  kubectl:
    namespace: argocd
    src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    state: present
