# Basic Settings
service:
  type: NodePort  # Suitable for Minikube
  proxyPort: 6032  # Default ProxySQL port for applications to connect

# Oracle Database Configuration 
mysql_servers:
  - address: adria-ora-sidb-primary-ext.orao-ha.svc.cluster.local  # Corrected service name
    port: 1521
    hostgroup: 0  # Primary
  - address: adria-ora-sidb-standby-ext.orao-ha.svc.cluster.local   # Corrected service name
    port: 1521
    hostgroup: 1  # Standby

# Simple Query Routing (Sends SELECT to hostgroup 1 - the standby)
mysql_query_rules:
  - active: 1
    match_pattern: "^SELECT" 
    destination_hostgroup: 1  
    apply: 1
service:
    type: NodePort  # Suitable for testing
    port: 6032     # Default admin port

secret:
  # This are the variables to set `admin_credentials`
  # WARNING: Set the `admin_credentials` variable to a non-default user other than admin`.
  #          ProxySQL reserves the default `admin` user for local connection via localhost only.
  admin_user: "proxysql-admin"
  admin_password: "proxysql"

admin_variables:
  debug: false

  ## The number of background threads that ProxySQL uses in order to process MySQL traffic
  threads: 4
  ## The maximum number of client connections that the proxy can handle.
  max_connections: 5048
  default_query_delay: 0
  ## Mechanism for specifying the maximal duration of queries to the backend MySQL (in ms)
  default_query_timeout: 3600000
  ## Enables or disables MySQL Monitor.
  #  ref: https://github.com/sysown/proxysql/wiki/Monitor-Module
  monitor_enabled: false
  # monitor_username: "monitor"
  # monitor_password: "monitor"
  # monitor_history: 600000

## Configures ProxySQL mysql users.
#  For MySQL 8.0 paswords must be mysql_native_password.
#  ref: https://github.com/sysown/proxysql/wiki/MySQL-8.0
#
mysql_users:
   - username: "SYS AS SYSDBA"
     password: "Kube#adria#2024"
     default_hostgroup: 0
     max_connections: 200
     default_schema: "information_schema"
     active: 1

