{
 "title": "OracleDB Monitoring - performance and table space stats",
 "description": "Use oracledb exporter for oracle database monitoring. Compared with other dashboards, tablespace monitoring is added, which can be expanded to set tablespace alarms",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values(oracledb_up, instance)"
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Database status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_up{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Active sessions ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "oracledb_sessions_value{instance=\"$host\",status=\"ACTIVE\",type=\"USER\"}"
    }
   ]
  },
  {
   "title": "User rollback",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_activity_user_rollbacks{instance=\"$host\"}",
     "legendFormat": "{{descr}} - User rollback"
    }
   ]
  },
  {
   "title": "User commits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracledb_activity_user_commits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Primary SIDB RAM Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=\"adria-ora-sidb-primary-bptyw\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Primary Instance CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{pod=\"adria-ora-sidb-primary-bptyw\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracledb_tablespace_bytes", "legendFormat": "{{tablespace}}" }
   ]
  },
  {
   "title": "Oracle cluster CPU Usage ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_cpu_usage_seconds_total{namespace=\"orao-ha\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oracle cluster Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"orao-ha\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top SQL by elapsed time running",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max(oracledb_obaas_top_sql_elapsed) by (sql_id, sql_text)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System I/O wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_system_io{instance=\"$host\"}",
     "legendFormat": "{{descr}} - System I/O wait"
    }
   ]
  },
  {
   "title": "Concurrent wait time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_concurrency{instance=\"$host\"}",
     "legendFormat": "{{descr}} - Concurrent wait time"
    }
   ]
  },
  {
   "title": "Resource utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracledb_resource_current_utilization{instance=\"$host\"}",
     "legendFormat": "Resource utilization - {{resource_name}} "
    }
   ]
  },
  {
   "title": "PGA Aggregate Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_obaas_db_system_value{name=\"pga_aggregate_limit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SGA Max Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_obaas_db_system_value{name=\"sga_max_size\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "User I/O wait",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "oracledb_wait_time_user_io{instance=\"$host\"}\t",
     "legendFormat": "{{descr}} - User I/O wait"
    }
   ]
  },
  {
   "title": "Final collection time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_exporter_last_scrape_duration_seconds{instance=\"$host\"}\t"
    }
   ]
  },
  {
   "title": "Total collection",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_exporter_scrapes_total{instance=\"$host\"}"
    }
   ]
  }
 ]
}