{
 "title": "TxEventQ Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(oracledb_teq_enqueued_msgs, inst_id)"
    }
   },
   {
    "name": "queue",
    "query": {
     "query": "label_values(oracledb_teq_enqueued_msgs{inst_id=\"$instance\"}, queue_name)"
    }
   },
   {
    "name": "subscriber",
    "query": {
     "query": "label_values(oracledb_teq_enqueued_msgs{inst_id=\"$instance\", queue_name=\"$queue\"}, subscriber_name)"
    }
   },
   {
    "name": "asm",
    "label": "disk group",
    "query": {
     "query": "label_values(oracledb_asm_diskgroup_free, name)"
    }
   },
   {
    "name": "wait_class",
    "query": {
     "query": "label_values(oracledb_wait_class_total_waits, wait_class)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  { "title": "TxEventQ Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "TxEventQ Status",
   "type": "stat",
   "description": "If TxEventQs are running or not",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_teq_total_queues{inst_id=~\"[[instance]]\"}"
    }
   ]
  },
  {
   "title": "Overall Enqueue/Dequeue Rate",
   "type": "graph",
   "description": "Aggregate enq/deq rates for all TxEventQs",
   "gridPos": { "h": 13, "w": 12, "x": 4, "y": 9 },
   "yaxes": [
    {
     "format": "short",
     "label": "Total Enqueue Rate (messages/s)"
    }
   ],
   "targets": [
    {
     "expr": "sum(rate(oracledb_teq_enqueued_msgs{inst_id=~\"[[instance]]\"}[3m]))",
     "legendFormat": "Total Enqueue Rate"
    },
    {
     "expr": "sum(rate(oracledb_teq_dequeued_msgs{inst_id=~\"[[instance]]\"}[3m]))",
     "legendFormat": "Total Dequeue Rate"
    }
   ]
  },
  {
   "title": "Overall Enqueue Messages",
   "type": "stat",
   "description": "Total enqueued messages for the entire queue system",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(oracledb_teq_enqueued_msgs{inst_id=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "Overall Dequeue Messages",
   "type": "stat",
   "description": "Total dequeued messages for the entire queue system",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(oracledb_teq_dequeued_msgs{inst_id=~\"[[instance]]\"})"
    }
   ]
  },
  {
   "title": "Total TxEventQ",
   "type": "stat",
   "description": "The number of TxEventQs running",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_teq_total_queues{inst_id=~\"[[instance]]\"}"
    }
   ]
  },
  {
   "title": "Overall Bytes In/Bytes Out Rate",
   "type": "graph",
   "description": "Approximate aggregate bytes-in/bytes-out rates for all TxEventQs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    {
     "format": "decbytes",
     "label": "Total Bytes In Rate (Bytes/Second)"
    }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_system_network_received_from_client{inst_id=~\"[[instance]]\"}[3m])",
     "legendFormat": "Total Bytes In Rate"
    },
    {
     "expr": "rate(oracledb_system_network_sent_to_client{inst_id=~\"[[instance]]\"}[3m])",
     "legendFormat": "Total Bytes Out Rate"
    }
   ]
  },
  {
   "title": "Total TxEventQ Subscriber",
   "type": "stat",
   "description": "The total number of subscribers for all TxEventQs",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_teq_total_subscribers{inst_id=~\"[[instance]]\"}"
    }
   ]
  },
  {
   "title": "TxEventQ Quick Lookup Table ",
   "type": "table-old",
   "description": "TxEventQ Quick Lookup Table: simply click on the metric name and order it increasingly or decreasingly, easy to identify a 'good' queue or a 'bad' queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(oracledb_teq_remained_msgs) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    },
    {
     "expr": "sum(oracledb_teq_message_latency_1) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    },
    {
     "expr": "sum(rate(oracledb_teq_enqueued_msgs[3m])) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    },
    {
     "expr": "sum(rate(oracledb_teq_dequeued_msgs[3m])) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    },
    {
     "expr": "sum(oracledb_teq_enqueued_msgs) by (queue_name)"
    },
    {
     "expr": "sum(oracledb_teq_dequeued_msgs) by (queue_name)"
    },
    {
     "expr": "sum(rate(oracledb_teq_dequeued_msgs[3m]))  by (queue_name) / sum(rate(oracledb_teq_enqueued_msgs[3m])) by (queue_name) ",
     "legendFormat": "{{queue_name}}"
    },
    {
     "expr": "sum(oracledb_teq_enqueued_msgs) by (queue_name) - sum(oracledb_teq_dequeued_msgs) by (queue_name)",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "TxEventQ Stat for $queue with Subscriber $subscriber",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "Enqueue/Dequeue Messages",
   "type": "graph",
   "description": "Total messages enqueued/dequeued to/from the TxEventQ.",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Total Enqueue (messages)" }
   ],
   "targets": [
    {
     "expr": "oracledb_teq_enqueued_msgs{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}",
     "legendFormat": "Total Eenqueue"
    },
    {
     "expr": "oracledb_teq_dequeued_msgs{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}",
     "legendFormat": "Total Dequeue"
    }
   ]
  },
  {
   "title": "Enqueue/Dequeue Rate",
   "type": "graph",
   "description": "Enq/deq rate for the TxEventQ.",
   "gridPos": { "h": 9, "w": 9, "x": 9, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "Enqueue Rate (messages/s)" }
   ],
   "targets": [
    {
     "expr": "rate(oracledb_teq_enqueued_msgs{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}[3m])",
     "legendFormat": "Enqueue Rate"
    },
    {
     "expr": "rate(oracledb_teq_dequeued_msgs{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}[3m])",
     "legendFormat": "Dequeue Rate"
    }
   ]
  },
  {
   "title": "TxEventQ Name",
   "type": "text",
   "description": "The name of TxEventQ.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 31 },
   "options": {
    "content": "<div style=\"text-align: center;\"><span style=\"color:green\"><b>$queue</b></span></div>"
   }
  },
  {
   "title": "Subscriber Name",
   "type": "text",
   "description": "The name of TxEventQ subscriber.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 33 },
   "options": {
    "content": "<div style=\"text-align: center;\"><span style=\"color:green\"><b>$subscriber</b></span></div>"
   }
  },
  {
   "title": "TxEventQ Depth (Remaining Messages)",
   "type": "graph",
   "description": "Total messages remained in the queue.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Remaining Message (messages)" }
   ],
   "targets": [
    {
     "expr": "oracledb_teq_remained_msgs{inst_id=~\"[[instance]]\", queue_name=~\"[[queue]]\", subscriber_name=~\"[[subscriber]]\"}",
     "legendFormat": "TxEventQ Depth"
    }
   ]
  }
 ]
}