apiVersion: v1
kind: Service
metadata:
  name: adria-pg-db-primary-loadbalancer
  namespace: pgo-ha
spec:
  ports:
  - name: postgres
    port: 5432
    protocol: TCP
    targetPort: postgres
  selector:
    postgres-operator.crunchydata.com/cluster: adria-pg-db
    postgres-operator.crunchydata.com/role: primary
  type: LoadBalancer
