apiVersion: v1
kind: ConfigMap
metadata:
  name: adria-init-sql
  namespace: pgo-ha
data:
  init.sql: |
    -- PUT SQL Script here (it can be used once during the PostgreSQL cluster deployement)
    
    