apiVersion: v1
kind: ConfigMap
metadata:
  name: adria-init-sql
  namespace: pgo-ha
data:
  init.sql: |
    -- Create a group 'dev' and grant privileges
    CREATE GROUP dev;
    GRANT CONNECT ON DATABASE cih TO "dev-cih-ro" ;
    GRANT USAGE ON SCHEMA public TO "dev-cih-ro" ;
    GRANT CREATE ON SCHEMA public TO "dev-cih-ro" ;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "dev-cih-ro" ;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "dev-cih-ro" ;

    