apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: adria-pg-db
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.2-0
  postgresVersion: 16
  # to Handle secure replication 
  customReplicationTLSSecret:
    name: adria-pg-db-repl-tls
  # to handle secure communication 
  customTLSSecret:
    name: adria-pg-db-tls
  databaseInitSQL:
    key: init.sql
    name: adria-init-sql
  instances:
    - name: adria-postgres-db
      replicas: 3
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "2000m"
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 4Gi
      #Write Ahead Log config 
      walVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: adria-pg-db
                  postgres-operator.crunchydata.com/instance-set: adria-postgres-db
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.49-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
  #enabling monitoring
  monitoring:
    pgmonitor:
      exporter:
        image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.5.1-0
  users:
    - name: adria-dba
      databases:
        - cih
        - cdm 
        - sgabs
        - attijari
        - bcp 
      options: 'SUPERUSER'
    - name: dev-cih
      databases:
        - cih
      options: 'SUPERUSER'
    - name: dev-cih-ro 
      databases:
        - cih
      options: 'NOSUPERUSER'      
  #enabling synchronous communication between replicas 
  patroni:
  #It allows you to enable switchovers in your PostgresClusters, target a specific instance as the new primary, and run a failover if your PostgresCluster has entered a bad state.
    switchover:
      enabled: true
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        parameters:
          synchronous_commit: "on"
          archive_timeout: 60  
          max_connections: 10000
          max_parallel_workers: 2
          max_worker_processes: 2
          shared_buffers: 1GB
          work_mem: 2MB
  
  # pgbouncer proxy
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.21-3
      replicas: 2
      config:
        global:
          max_client_conn: "10000"
      # env:
      #   - name: MAX_CLIENT_CONN
      #     value: "10000"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: adria-pg-db
                  postgres-operator.crunchydata.com/role: pgbouncer
  