apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: adria-pg-db
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.2-0
  postgresVersion: 16
  # to Handle secure replication 
  customReplicationTLSSecret:
    name: adria-pg-db-repl-tls
  # to handle secure communication 
  customTLSSecret:
    name: adria-pg-db-tls


# TODO --- add resources 
