#
# Copyright (c) 2022, Oracle and/or its affiliates. 
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

## Append samples you want in your CSV to this file as resources ##
resources:


  - sidb/singleinstancedatabase.yaml
  # - sidb/singleinstancedatabase_standby.yaml
  # - sidb/dataguardbroker.yaml
  # - observability/databaseobserver.yaml
  # - sidb/proxysql.yml
  
 
  # +kubebuilder:scaffold:manifestskustomizesamples
