apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-backup

spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi  
  storageClassName: standard  

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: primary-db-backup

spec:
  schedule: "* * * * *"   
  concurrencyPolicy: Forbid  
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector: 
            kubernetes.io/hostname: <your-node-name>
          volumes:
            - name: oracle-backup-volume
              persistentVolumeClaim:
                claimName: oracle-backup
          restartPolicy: Never   
          hostPID: true
          hostNetwork: true
          containers: # <--- The missing 'containers' field
            - name: oracle-backup
              command: ["/bin/bash", "-c"]
              args:
                - |
                  rman target / @/backup_script.sh

              volumeMounts:
                - name: oracle-backup-volume
                  mountPath: /backup  
                - name: backup-script
                  configMap:
                    name: oracle-backup-script

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-backup-script
 
data:
  backup_script.sh: |
    #!/bin/bash
    rman target / <<EOF
    backup database plus archivelog;
    delete noprompt obsolete;
    exit;
    EOF
