apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-backup

spec:
  accessModes:
    - ReadWriteOnce  # Allow read-write access by a single node
  resources:
    requests:
      storage: 2Gi  # Request 20 GiB of storage (adjust as needed)
  storageClassName: standard  # Use the 'standard' StorageClass in Minikube
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: primary-db-backup
  
spec:
  schedule: "* * * * *"   # Set to run every minute, but won't do anything
  concurrencyPolicy: Forbid  # Prevent overlapping runs
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: fk
              image: busybox:latest  # A minimal image for testing
              command: ["/bin/sleep", "60"] # Sleep for 60 seconds
              volumeMounts:
                - name: oracle-backup-volume
                  mountPath: /backup  # Mount the PVC at /backup inside the container
          restartPolicy: Never   # Don't restart the pod if it fails
          volumes:
            - name: oracle-backup-volume
              persistentVolumeClaim:
                claimName: oracle-backup
