#This the primary ORACLE Database EE instance 
apiVersion: database.oracle.com/v1alpha1
kind: SingleInstanceDatabase
metadata:
  name: adria-ora-sidb-standby1

spec:
  ## Use only alphanumeric characters for sid up to a maximum of 8 characters
  sid: ORCLS1
  ## Specify a source database ref to copy/clone from any SIDB in current K8s cluster instead of creating a fresh one
  ## If cloning from an external containerized DB which could be either standalone or in any K8s cluster,
  ## specify connect string as `<host>:<port>/<service_name>` instead of source database ref
  cloneFrom: ""
  
  pdbName: adriadb

  ## Reference to a source primary database from which
  ## Format: 1. Intra-cluster: you can give name of the primary database or the database connect string in `<host>:<port>/<service_name>` format
  ##         2. Inter-cluster: Database connect string in `<host>:<port>/<service_name>` format
  primaryDatabaseRef: "adria-ora-sidb-primary"

  ## Enable this flag for creating Physical Standby Database
  createAs: standby

  ## DB edition. N/A if cloning from a Source DB in current K8s cluster (if cloneFrom is set to a database ref)
  ## Valid values for edition are enterprise, standard or express
  edition: enterprise
  
  ## Secret containing SIDB password mapped to secretKey. secretKey defaults to oracle_pwd
  ## Should refer to adminPassword of Source DB if cloning from a Source DB (i.e if cloneFrom is set)
  ## This secret will be deleted after creation of the database unless keepSecret is set to true which is the default
  adminPassword:
    secretName: admin-password  
    secretKey: sidb-admin-password
    keepSecret: true

  ## DB character set. N/A if cloning from a Source DB (if cloneFrom is set)
  charset: AL32UTF8

  image:
   #Adria Repository Name 
    pullFrom: container-registry.oracle.com/database/enterprise:21.3.0.0
    pullSecrets: regcred
    prebuiltDB: false

  ## size is the required minimum size of the persistent volume
  ## storageClass is specified for automatic volume provisioning
  ## accessMode can only accept one of ReadWriteOnce, ReadWriteMany
  ## volumeName is optional. Specify for binding to a specific PV and set storageClass to an empty string to disable automatic volume provisioning
  persistence:
    size: 6Gi
    ## a storage class should be created, in local env we will use `standard` (default minikube storage class)
    storageClass: "linode-block-storage-retain"
    accessMode: "ReadWriteOnce"
    volumeName: ""

  ## Type of service . Applicable on cloud enviroments only
  ## if loadBalService : false, service type = "NodePort" else "LoadBalancer"
  loadBalancer: false
  

  serviceAccountName: default

  replicas: 1