---
- name: Setup Docker
  ansible.builtin.include_role:
    name: common
    tasks_from: docker_setup

- name: Setup Kubernetes
  ansible.builtin.include_role:
    name: common
    tasks_from: kubernetes_setup

- name: Initialize Kubernetes cluster
  ansible.builtin.include_tasks: init_kubernetes_cluster.yml

- name: Calico network setup
  ansible.builtin.include_tasks: calico_setup.yml

- name: Generate join command and copy to local file
  ansible.builtin.include_tasks: join_command.yml
