---
# handlers file for k8s_master

- name: "Start Docker"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: "Restart Containerd"
  ansible.builtin.service:
    name: containerd
    state: restarted
    enabled: true
