# values.yaml for Prometheus on Linode Kubernetes Engine (LKE)

# Global Settings (Adjust as needed)
serviceAccounts:
  server:
    create: true

# Storage Configuration (Important for Linode LKE)
persistence:
  enabled: true
  storageClassName: "linode-block-storage-retain"  # Replace with the actual storage class name you want to use on Linode
  size: 8Gi  # Or your desired storage size

# Server Configuration
server:
  serviceMonitorSelector:
    matchLabels:
      release: prometheus  # Match your ServiceMonitor label

  # Scrape Configuration for Oracle Exporter
  scrapeConfigs:
    - job_name: 'oracle-exporter'
      metrics_path: '/metrics'
      scrape_interval: 15s
      scrape_timeout: 10s
      static_configs:
        - targets: ['obs-svc-obs-sample.orao-ha:9161']   # Ensure correct service name and port
  
  # Expose Prometheus UI if needed (Optional)
  service:
    type: LoadBalancer 
  
# Disable Alertmanager if using Grafana (Optional)
alertmanager:
  enabled: false

# Enable kube-state-metrics for Kubernetes monitoring (Optional)
kubeStateMetrics:
  enabled: true
