# values.yaml for Prometheus (with Oracle DatabaseObserver configuration)

# Global settings
serviceAccounts:
  server:
    create: true

server:
  serviceMonitorSelector:
    matchLabels:
      release: prometheus  # Match your ServiceMonitor label

  # Configure additional scrape configurations 
  scrapeConfigs:
    - job_name: 'oracle-exporter' # Oracle Database Exporter Job
      metrics_path: '/metrics'
      scrape_interval: 15s
      scrape_timeout: 10s
      static_configs:
      - targets: ['obs-svc-obs-sample.orao-ha.svc.cluster.local:9161'] 
        # Replace 'obs-svc-obs-sample.orao-ha.svc.cluster.local:9161' with your DatabaseObserver service details
        

# Other Prometheus components (optional, customize as needed)
alertmanager:
  enabled: false  # Disable if using Grafana for alerting

kubeStateMetrics:
  enabled: true   # Collect Kubernetes cluster metrics

# Additional configuration options...
# (See the Prometheus Helm chart documentation for more details)
