---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  # name: letsencrypt-issuer
  name: ca-issuer
  namespace: cert-manager
spec:
  ca:
    secretName: root-secret

# ------------------------ to Work with Let's encrypt issuer
  # acme:
  #   email: myemail@company.com
  #   server: https://acme-staging-v02.api.letsencrypt.org/directory
  #   privateKeySecretRef:
  #     # Secret used to store the account's private key.
  #     name: example-issuer-account-key
  #   # Add a ACME HTTP01 challenge solver
  #   solvers:
  #   - http01:
  #       ingress:
  #         ingressClassName: haproxy