# Default values for proxysql.

image:
  registry: docker.io
  repository: proxysql/proxysql
  # tag: ""  Leave tag as null to get the latest version
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: 

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 999
  runAsUser: 999
  runAsGroup: 999

securityContext: {}

## ProxySQL service configuration
service:
  type: ClusterIP
  proxyPort: 6033
  adminPort: 6032
  webPort: 6080

# ... (Other sections like resources, nodeSelector, tolerations, etc. remain unchanged)

secret:
  admin_user: admin
  admin_password: "monitor"  # Set a strong password

admin_variables:
  debug: false
  cluster_enabled: false   # Disabled for single-instance ProxySQL
  # ... (Other admin variables unchanged) ...

mysql_variables:
  threads: 4 
  max_connections: 2048 
  default_query_delay: 0
  default_query_timeout: 36000000 
  have_compress: true
  poll_timeout: 2000
  interfaces: "0.0.0.0:6033;/tmp/proxysql.sock" 

  stacksize: 1048576                
  server_version: "21c"              
  connect_timeout_server: 3000      
  monitor_username: "c##monitor"       
  monitor_password: "monitor" # Set a strong password
  monitor_history: 600000
  monitor_connect_interval: 5000      # More frequent monitoring
  monitor_ping_interval: 2000
  monitor_read_only_interval: 1500
  monitor_read_only_timeout: 500
  ping_interval_server_msec: 120000  
  ping_timeout_server: 500
  commands_stats: true
  sessions_sort: true
  connect_retries_on_failure: 10


# Oracle database connections (replace placeholders)
mysql_servers:
  - address: "adria-ora-sidb-primary.orao-ha.svc.cluster.local"
    port: 1521                       
    hostgroup: 0  # Writer group (for the primary)
    max_connections: 1000
  - address: "adria-ora-sidb-standby.orao-ha.svc.cluster.local"   
    port: 1521                       
    hostgroup: 1  # Reader group (for the standby)
    max_connections: 1000
  


# Oracle user (replace placeholders)
mysql_users:
  - username: "c##monitor"
    password: "monitor" 
    default_hostgroup: 0 # Default to writer group 
    active: 1 

mysql_query_rules: 
- active: 1
  match_pattern: "^(SELECT|WITH)"
  destination_hostgroup: 1
  apply: 1
- active: 1
  match_pattern: ".*"
  destination_hostgroup: 0
  apply: 1


# Disabled Proxysql Cluster and relevant settings
use_default_proxysql_servers: false
proxysql_cluster:
  enabled: false

# ... (Rest of the configuration remains the same)
